### ISSUE TITLE
Titulo

### ISSUE THREAD

**Issue by weslleyandrade** [otaviojava/imergindo-jvm-book#1]
Otávio, bom dia.
Primeiramente parabéns e obrigado pelo material produzido, tenho certeza que vai agregar muito tais informações. 

Bom, abri esse issue para recomendar a adição do link "http://otaviojava.gitbooks.io/imergindo-na-jvm/" no titulo desse projeto, facilitando a leitura de quem não conhece a url em questão.

Mais uma vez lhe agradeço pelas informações compartilhadas.

**Comment by otaviojava** [comment]
Olá @weslleyandrade  tudo bem?
Primeiramente, desculpa pela demora em responder.
Acabei de adicionar o link no título.
Muito obrigado pela sugestão.
