### ISSUE TITLE
Número de implementações da JVM

### ISSUE THREAD

**Issue by felipe-araujo** [otaviojava/imergindo-jvm-book#8]
Olá Otávio,
Primeiramente, parabéns pelo material. 

Só queria alertar para o trecho seguinte da seção "Falando um pouco sobre a JVM":
_Ao contrário do que muitas pessoas imaginam, existem milhões de máquinas virtuais, dentre as mais populares está a HotSpot._
Na verdade, apesar de existirem várias implementações, acredito que não chegamos nem perto de milhões ainda.
Veja, por exemplo, http://www.quora.com/How-many-JVM-implementations-are-there

Abraço

**Comment by otaviojava** [comment]
Olá @felipe-araujo tudo bem?
Obrigado, dei uma forçada na hipérbole.
Modifiquei para dezenas.
O que você acha?

**Comment by felipe-araujo** [comment]
Opa,
Legal, acho que assim dá uma ideia melhor do número de implementações. 

Abraço!

**Comment by otaviojava** [comment]
:smile: obrigado.
